language: python
dist: xenial
matrix:
  include:
    - python: "3.6"
      env: TOX_POSARGS="-e py36"
    - python: "3.7"
      env: TOX_POSARGS="-e py37"
install:
  - travis_retry pip install tox
script:
  - cd cli && tox $TOX_POSARGS