stream:
  image:
    repository: blockchainetl/iotex-etl
    tag: 1.0.0
config:
  PROVIDER_URI: "grpcs://api.mainnet.iotex.one:443"
  STREAM_OUTPUT: "projects/<your_project>/topics/mainnet"
  GCS_PREFIX: "gs://<your_bucket>/iotex-etl/streaming"
  LAG_BLOCKS: "10"
  ENTITY_TYPES: "block,action,log,transaction_log"