name: Publish DockerHub

on:
  push:
    tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Publish to DockerHub
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: blockchainetl/iotex-etl
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
          tag_semver: true